export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

export default function About() {
    return (
        <div>
            <h1>About Us</h1>
            <p>This is the about page.</p>
        </div>
    );
}
